---
- name: Preparando Workstashion
  hosts: localhost
  connection: local
  tasks:

    - name: Installing Linux Apps
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - htop
          - curl
          - wget
          - ncdu
          - tree
          - apt-transport-https
          - ca-certificates
          - gnupg
          - python3-pip
          - python3-env
          - make
          - git
          - bash-completion
          - gnupg-agent
          - zsh
          - flameshot
          - fonts-hack
          - tilix
          - virtualbox
          - mlocate
          - krita
          - jq
          - mtr
          - lsb-release
          - build-essential
          - software-properties-common
          - ubuntu-keyring
          - jmeter-java
          - net-tools
          - openjdk-11-jdk
          - snap

    - block:
      - name: Installing AWS CLI via pip3
        become: true
        pip:
          name: awscli
          executable: pip3
    
    - block:
      - name: Install Google Key
        become: true
        apt_key: 
          url: 'https://dl.google.com/linux/linux_signing_key.pub'
          state: present
      - name: Install Google Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
          state: present
          filename: google-chrome
      - name: Install Google Chrome
        become: true
        apt:
          name: google-chrome-stable

    - block:
      - name: Install Sublime Key
        become: true
        apt_key:
          url: 'https://download.sublimetext.com/sublimehq-pub.gpg'
          state: present
      - name: Install Sublime Repository
        become: true
        apt_repository: 
          repo: 'deb [arch=amd64] https://download.sublimetext.com/ apt/stable/'
          state: present
          filename: sublime-text
      - name: Install Sublime
        become: true
        apt:
          name: sublime-text


    - block:
      - name: Install DBeaver Key
        become: true
        apt_key:
          url: 'https://dbeaver.io/debs/dbeaver.gpg.key'
          state: present
      - name: Install DBeaver Repository
        become: true
        apt_repository: 
          repo: 'deb [arch=amd64] https://dbeaver.io/debs/dbeaver-ce /'
          state: present
          filename: dbeaver-ce_22.0.5_amd.deb
      - name: Install DBeaver
        become: true
        apt:
          name: dbeaver-ce

    - block:
      - name: Installing gomplate 3.9.0
        become: true
        get_url:    
          url: 'https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64'
          dest: /usr/local/bin/gomplate
          mode: 755 

    - block:
      - name: Adding Longsleep/Golang Backports Repository
        become: true
        apt_repository:
          repo: 'ppa:longsleep/golang-backports'
      - name: Install Golang 
        become: true
        apt:
          name: golang-go

    - block:
      - name: Adding Android-Studio Repository
        become: true
        apt_repository:
          repo: 'ppa:maarten-fonville/android-studio'
      - name: Install Android-Studio
        become: true
        apt:
          name: android-studio

    - block:
      - name: Install Snap - Core 18
        become: true
        shell: 
          cmd: 'snap install core18'
          warn: false
      - name: Install MailSpring
        become: true
        shell:
          cmd: 'snap install mailspring'
          warn: false
      - name: Install Postman
        become: true
        shell:
          cmd: 'snap install postman'
          warn: false
      - name: Install Intellij
        become: true
        shell:
          cmd: 'snap install intellij-idea-community --classic --edge'
          warn: false

    - block:
      - name: Install Microsoft Key
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present
      - name: Install VSCode Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
          state: present
          filename: vscode
      - name: Install Visual Studio Code
        become: true
        apt:
          name: code

      - name: Install Edge Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main'
          state: present
          filename: edge
      - name: Install Microsoft Edge
        become: true
        apt:
          name: microsoft-edge-stable    
      - name: Install Teams Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
          state: present
          filename: ms-teams
      - name: Install Teams
        become: true
        apt:
          name: teams
    - block:
      - name: Install Trivy
        become: true
        shell:
          cmd: 'curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh'
          warn: false

    - block:
      - name: Install FortiClient Key
        become: true
        apt_key:
          url: 'https://repo.fortinet.com/repo/6.4/ubuntu/DEB-GPG-KEY'
          state: present
      - name: Install FortiNet Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://repo.fortinet.com/repo/6.4/ubuntu xenial multiverse'
          state: present
          filename: forticlient
      - name: Install FortiClient
        become: true
        apt:
          name: forticlient
    - block: 
      - name: Install Docker Key
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/ubuntu/gpg'
          state: present
      - name: Install Docker Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
          state: present
          filename: docker-ce
      - name: Install Docker
        become: true
        apt:
          name: docker-ce
      - name: Adding existing user to group Docker
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          groups: docker 
          append: yes
      - name: Install Docker-Compose
        become: true
        get_url:
          url: 'https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64'
          dest: '/usr/local/bin/docker-compose'
          mode: 755
      - name: Install Docker Machine Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash'
          dest: '/etc/bash_completion.d/docker-machine'
      - name: Install Docker-Compose Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/compose/1.26.2/contrib/completion/bash/docker-compose'
          dest: '/etc/bash_completion.d/docker-compose'

    - block:  
      - name: Install Robo3t
        become: true
        shell:
          cmd: 'snap install robo3t-snap'
          warn: false
   
    - block:
      - name: Zoom - Client
        become: true
        shell: 
          cmd: 'snap install zoom-client'
          warn: false
    - block:
      - name: Adding Peek Repository
        become: true
        apt_repository:
          repo: 'ppa:peek-developers/stable'
      - name: Install Peek
        become: true
        apt:
          name: peek

    - block: 
      - name: Install Brave Key
        become: true
        apt_key:
          url: 'https://brave-browser-apt-release.s3.brave.com/brave-core.asc'
          state: present
      - name: Install Brave Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
          state: present
          filename: brave
      - name: Install Brave Browser
        become: true
        apt:
          name: brave-browser